name: wike
base: core24
adopt-info: wike
grade: stable
confinement: strict
platforms:
  amd64:
  armhf:
  arm64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

parts:
  wike:
    plugin: meson
    source: https://github.com/hugolabe/Wike.git
    source-tag: '3.1.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    build-environment:
      - PATH: /snap/webkitgtk-sdk/current/usr/bin:$PATH
      - XDG_DATA_DIRS: /snap/webkitgtk-sdk/current/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/webkitgtk-sdk/current/usr/lib:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
    stage-packages:
      - libjpeg9
    build-snaps:
      - webkitgtk-6-gnome-2404-sdk
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/wike.patch
    parse-info: [ usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml ]
    organize:
      snap/wike/current: .

plugs:
  webkitgtk-6-gnome-2404:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2404

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3.10/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
    plugs:
      - audio-playback
      - unity7
      - network
      - network-status
    common-id: com.github.hugolabe.Wike
